N_app/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/',include("notes.urls")),
]

notes/urls.py
from django.urls import path
from .views import NotesListView,update_Notes,delete_notes,CreateNewNote,SearchResultView,NoteDetials

urlpatterns=[
    path('',NotesListView.as_view(),name="notes"),
    path('update/<int:id>',update_Notes,name='update'),
    path('delete/<int:id>',delete_notes,name='delete'),
    path('new/',CreateNewNote.as_view(),name='addnew'),
    path('search/',SearchResultView.as_view(),name='search_result'),
    path('note/<int:pk>/',NoteDetials.as_view(),name='note_details'),
]

notes/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Notes(models.Model):
    title=models.CharField(max_length=500,null=True,blank=True)
    notes=models.TextField()
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self): # new
        return reverse("note_details", args=[str(self.id)])

notes/forms.py
from django import forms
from .models import Notes
class Notesfrom(forms.ModelForm):
    class Meta:
        model=Notes
        fields=[
            'title',
            'notes',
        ]

notes/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView,CreateView,DetailView
from django.urls import reverse_lazy
from django.db.models import Q
from .models import Notes
from .forms import Notesfrom

# Create your views here.
class NotesListView(ListView):
    model=Notes
    template_name='notes.html'
    
def update_Notes(request,id):
    note_id=Notes.objects.get(id=id)
    if request.method == 'POST':
        note_save=Notesfrom(request.POST,request.FILES,instance=note_id)
        if note_save.is_valid():
            note_save.save()
            return redirect('/notes')
    else:
        note_save=Notesfrom(instance=note_id)
    context={
        'form':note_save,
    }
    return render(request,'update.html',context)
        
def delete_notes(request,id):
    note_delete=Notes.objects.get(id=id)
    if request.method == 'POST':
        note_delete.delete()
        return redirect('/notes')
    return render(request,'delete.html')

class CreateNewNote(CreateView):
    model=Notes
    template_name="addnewnote.html"
    fields={
        'title',
        'notes',   
    }
    success_url=reverse_lazy("notes")
    
    
class SearchResultView(ListView):
    model=Notes
    context_object_name="notes"
    template_name="searchresult.html"
    
    def get_queryset(self):
        query=self.request.GET.get("q")
        return Notes.objects.filter(Q(title__icontains=query)|Q(notes__icontains=query))

class NoteDetials(DetailView):
    model=Notes
    context_object_name="note"
    template_name="detials.html"

templates/addnewnote.html
{%extends 'base.html'%}
{% load crispy_forms_tags %}
{%block content%}
<div style="direction: rtl;" class="wrapper">

    <!-- Content Wrapper. Contains page content -->
    <div   class="content-wrapper">
      <!-- Content Header (Page header) -->
  <div  class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Add New Note </h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form  method="POST" enctype="multipart/form-data">
      {%csrf_token%}
        <div class="card-body">
          
          {{form|crispy}}
  
          
        </div>
        <!-- /.card-body -->
  
        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      </form>
    </div>
  </div>
  </div>
  
{%endblock content%}

templates/base.html
{%load static%}
<!DOCTYPE html>
<html  lang="ar">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
  
    <title>Notes App</title>
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'plugins/jquery_datepacker/jquery_ui.css'%}">
    <!-- IonIcons -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte_ar.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  </head>
  <body dir="rtl" class="hold-transition sidebar-mini">

 {% include 'parts/nav.html' %}
 {% include 'parts/sidebar.html' %}
 {% block content %}

 {% endblock content%}
 {% include 'parts/footer.html' %}
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<script src="{% static 'plugins/jquery_datepacker/jquery_ui.js' %}"></script>

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js'%}"></script>
<!-- Bootstrap -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE -->
<script src="{% static 'dist/js/adminlte.js'%}"></script>
<!-- OPTIONAL SCRIPTS -->

<script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>

<script src="{% static 'dist/js/demo.js' %}"></script>
</body>
</html>

templates/delete.html
{%extends 'base.html'%}
{%block content%}

<div style="direction: rtl;" class="wrapper">

    <!-- Content Wrapper. Contains page content -->
    <div   class="content-wrapper">
      <!-- Content Header (Page header) -->
  <div  class="card card-danger">
      <div class="card-header">
        <h3 class="card-title">Delete the Note</h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form  method="POST" enctype="multipart/form-data">
      {%csrf_token%}
        <div class="row">
          
       <p class="p-3">Are you really sure to delete this notes?</p>
   
        </div>
        <!-- /.card-body -->
  
        <div class="card-footer">
          <button type="submit" class="btn btn-danger">Delete</button>
  
          <a href="{% url 'notes' %}" type="submit" class="btn btn-primary">Return</a>
        </div>
      </form>
    </div>
  </div>
  </div>
    
{%endblock content%}

templates/detials.html
{% extends 'base.html'%}
{% block title %}Details{% endblock title %}
{%block content%}

<div style="direction: rtl;" class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div   class="content-wrapper p-5">
      <!-- Content Header (Page header) -->

              <div class="row mb-2">
                <div class="col-sm-6">
                  <h1>Detail</h1>
                </div>
 
              </div>
      
          <!-- Main content -->
                          
            <!-- Default box -->

            <div class="card card-solid" style="width: 18rem;">
              <div class="card-body pb-0">
                
                            <h2 class="lead"><b>{{ note.title }}</b></h2>
                      <div class="card-body">
                        {{ note.notes}}
                      </div>
                      
                      <div class="card-footer">
                        <div class="text-right">
                          <a href="{% url 'delete' note.id %}" class="btn btn-sm bg-danger">
                            <i class="fas fa-trash">delete</i>
                          </a>
                          <a href="{% url 'update' note.id %}" class="btn btn-sm btn-primary">
                            <i class="fas fa-book"></i> update
                          </a>
                        </div>
                      </div>
                    
                </div>
                
              </div>
                <!-- /.card-body -->
                
                <!-- /.card-footer -->
            </div>
            
            <!-- /.card -->
      
          <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
      
    </div>
    <!-- /.content-wrapper -->
  </div>  
{%endblock content%}

templates/notes.html
{%extends 'base.html'%}
{% block title %}Notes{% endblock title %}
{%block content%}
 {% comment %}
{% for note in notes_list %}
<div class="card">
  <div class="card-header">
    <span class="font-weight-bold">{{ note.title }}</span> &middot;
    </div>
    <div class="card-body">
        {{ note.notes }}
     </div>
     <div class="card-footer text-center text-muted">
        <a href="#">Edit</a> | <a href="#">Delete</a>
      </div>
     
  </div>
<br />

{% endfor %} {% endcomment %}

<div style="direction: rtl;" class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div   class="content-wrapper p-5">
      <!-- Content Header (Page header) -->

              <div class="row mb-2">
                <div class="col-sm-6">
                  <h1>Notes</h1>
                </div>
 
              </div>
      
          <!-- Main content -->
          <section class="content row row-cols-4">                  
            <!-- Default box -->
            {% for note in notes_list %}
            <div class="card card-solid" style="width: 18rem;">
              <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch">
                      <div class="card-body pt-0">
                        <div class="row">
                          <div class="colcol-sm-6">
                            <h2 class="lead"><b> <a href="{{ note.get_absolute_url }}">{{note.title}}</a> </b></h2>
                          </div>
                        </div>
                      </div>
                      <div class="card-body">
                        {{ note.notes}}
                      </div>
                      
                      <div class="card-footer">
                        <div class="text-right">
                          <a href="{% url 'delete' note.id %}" class="btn btn-sm bg-danger">
                            <i class="fas fa-trash">delete</i>
                          </a>
                          <a href="{% url 'update' note.id %}" class="btn btn-sm btn-primary">
                            <i class="fas fa-book"></i> update
                          </a>
                        </div>
                      </div>
                    
                </div>
                   <!-- نهاية الكتاب -->
              </div>
                <!-- /.card-body -->
                
                <!-- /.card-footer -->
            </div>
              {% endfor %}
            <!-- /.card -->
      
          </section>
          <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
      
    </div>
    <!-- /.content-wrapper -->
  </div>  
{%endblock content%}

templates/parts/footer.html
      <!-- Main Footer -->
      <footer class="main-footer">
        <strong>Copyright &copy; 2021-2022 <a href="https://www.facebook.com/profile.php?id=100007880388921">Mohamed El-saidy</a>.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            <a target="_blank" href="https://www.facebook.com/profile.php?id=100007880388921"><i class="fab fa-lg ml-1 fa-facebook"></i></a>
            <a target="_blank" class="text-warning" href="https://www.instagram.com/elsaidy572/"><i class="fab fa-lg ml-1 fa-instagram"></i></a>
            <a class="btn-floating btn btn-tw" type="button" role="button" title="Share on twitter" href="https://twitter.com/Mohamed49830451?t=P9xfg8SGqDggvuAwshr4Mw&s=35"rel="noopener"><i class="fab fa-lg ml-1 fa-twitter"></i>
</a>
        </div>
      </footer>

templates/parts/nav.html
 <!-- في المكان ده هحط الناف بار -->

  <!-- Navbar -->
  <nav  class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'notes' %}" class="nav-link">Notes</a>
      </li>

    </ul>

    <!-- SEARCH FORM -->
    <form method="GET" action="{% url 'search_result' %}" class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" name="q" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>
  </nav>
  <!-- /.navbar -->

templates/parts/sidebar.html
  <!-- في المكان ده هحط سلايد بار -->

  <!-- Main Sidebar Container -->
  <aside style="position: fixed;" class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="" class="brand-link">
      <span class="brand-text font-weight-light">Notes_app</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
        </div>
        <div class="info">
          <a href="https://www.facebook.com/profile.php?id=100007880388921" class="d-block">Mohamed El-saidy</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-copy"></i>
              <p>
                Notes
                <i class="fas fa-angle-left right"></i>
                
              </p>
            </a>
            <ul class="nav nav-treeview">
              
                  <li class="nav-item">
                    <a id="addcat" href="{% url 'addnew' %}" class="nav-link">
                        <i class="fa fa-plus "></i>
                        <p  class="text-light"> Add New </p>
                    </a>
                  </li>
            </ul>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

templates/searchresult.html
{%extends 'base.html'%}
{% block title %}Search Result {% endblock title %}
{%block content%}

<div style="direction: rtl;" class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div   class="content-wrapper p-5">
      <!-- Content Header (Page header) -->

              <div class="row mb-2">
                <div class="col-sm-6">
                  <h1>Search Result</h1>
                </div>
 
              </div>
      
          <!-- Main content -->
          <section class="content row row-cols-4">                  
            <!-- Default box -->
            {% for note in notes %}
            <div class="card card-solid" style="width: 18rem;">
              <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch">
                      <div class="card-body pt-0">
                        <div class="row">
                          <div class="colcol-sm-6">
                            <h2 class="lead"><b>{{ note.title }}</b></h2>
                          </div>
                        </div>
                      </div>
                      <div class="card-body">
                        {{ note.notes}}
                      </div>
                      
                      <div class="card-footer">
                        <div class="text-right">
                          <a href="{% url 'delete' note.id %}" class="btn btn-sm bg-danger">
                            <i class="fas fa-trash">delete</i>
                          </a>
                          <a href="{% url 'update' note.id %}" class="btn btn-sm btn-primary">
                            <i class="fas fa-book"></i> update
                          </a>
                        </div>
                      </div>
                    
                </div>
         
              </div>
                <!-- /.card-body -->
                
                <!-- /.card-footer -->
            </div>
              {% endfor %}
            <!-- /.card -->
      
          </section>
          <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
      
    </div>
    <!-- /.content-wrapper -->
  </div>  
{%endblock content%}

templates/update.html
{%extends 'base.html'%}
{% load crispy_forms_tags %}
{%block content%}
<div style="direction: rtl;" class="wrapper">

    <!-- Content Wrapper. Contains page content -->
    <div   class="content-wrapper">
      <!-- Content Header (Page header) -->
  <div  class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Update the Note </h3>
      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form  method="POST" enctype="multipart/form-data">
      {%csrf_token%}
        <div class="card-body">
          
          {{form|crispy}}
  
          
        </div>
        <!-- /.card-body -->
  
        <div class="card-footer">
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      </form>
    </div>
  </div>
  </div>
  
{%endblock content%}